name: Keep Render Alive

on:
  schedule:
    - cron: "*/12 * * * *"   # Runs every 12 minutes
  workflow_dispatch:          # Allows manual run

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping API
        run: curl -s https://e-commerce-api-cb8d.onrender.com/ping

      - name: Ping Server
        run: curl -s https://e-commerce-server-xezh.onrender.com/ping
